[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

monitor_speed = 115200

build_flags =
    -D USB_MIDI_AUDIO_SERIAL
    ;-D USB_AUDIO

lib_deps =
    ; adafruit/Adafruit Keypad @ ^1.3.0
    ; adafruit/Adafruit NeoPixel @ ^1.12.3
    ; paulstoffregen/Encoder @ ^1.4.4
    ; https://github.com/PaulStoffregen/SerialFlash.git
    ; https://github.com/adafruit/Adafruit_Seesaw
    ; https://github.com/adafruit/Adafruit_ILI9341
    ; https://github.com/adafruit/Adafruit-GFX-Library
    ; https://github.com/PaulStoffregen/Audio.git
    ; https://github.com/crudlabs/StevesAwesomeButton

lib_extra_dirs = lib
lib_ldf_mode = deep+
